/**
 * This file is part of Atomic Tagging.
 * 
 * Atomic Tagging is free software: you can redistribute it and/or modify it under the terms of the GNU General Public
 * License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later
 * version.
 * 
 * Atomic Tagging is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License along with Atomic Tagging. If not, see
 * <http://www.gnu.org/licenses/>.
 */
package org.atomictagging.core.services;

import java.util.List;

import org.atomictagging.core.types.IMolecule;

/**
 * This is the entity based service for molecules. In provides CRUD as well as advanced search operations for molecules.
 */
public interface IMoleculeService {

	/**
	 * Returns the molecule with the given ID from the database.
	 * 
	 * @param moleculeId
	 * @return The molecule with the given ID or null, if no molecule was found
	 */
	IMolecule find( long moleculeId );


	/**
	 * Returns all molecules from the DB that are either tagged with the given tags or contain an atom that is tagged
	 * with those tags.
	 * 
	 * @param tags
	 * @return List of molecules as read from the DB.
	 */
	List<IMolecule> find( List<String> tags );


	/**
	 * Saves a molecule and returns the ID as generated by the database.
	 * 
	 * @param molecule
	 * @return The ID of the saved molecule as returned from the DB.
	 */
	long save( IMolecule molecule );


	public List<IMolecule> findByAtomData( final String data );
}
